receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 192
    spike_limit_mib: 48

  resource:
    attributes:
      - key: service.environment
        value: production
        action: upsert

exporters:
  elasticsearch:
    endpoints: ["https://opensearch:9200"]
    logs_index: mintstack-logs
    traces_index: mintstack-traces
    user: admin
    password: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    tls:
      insecure_skip_verify: true
  
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: mintstack

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch]
  
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
