KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="${KAFKA_SASL_PASSWORD}"
    user_kafka="${KAFKA_SASL_PASSWORD}";
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="${KAFKA_SASL_PASSWORD}";
};
